package com.uwb.bt2j.aligner;

public enum Opts {
	ARG_ORIG(256),             // --orig
	ARG_SEED(257),                   // --seed
	ARG_SOLEXA_QUALS(258),           // --solexa-quals
	ARG_VERBOSE(259),                // --verbose
	ARG_STARTVERBOSE(260),           // --startverbose
	ARG_QUIET(261),                  // --quiet
	ARG_METRIC_IVAL(262),            // --met
	ARG_METRIC_FILE(263),            // --met-file
	ARG_METRIC_STDERR(264),          // --met-stderr
	ARG_METRIC_PER_READ(265),        // --met-per-read
	ARG_REFIDX(266),                 // --refidx
	ARG_SANITY(267),                 // --sanity
	ARG_PARTITION(268),              // --partition
	ARG_INTEGER_QUALS(269),          // --int-quals
	ARG_FILEPAR(270),                // --filepar
	ARG_READS_PER_BATCH(271),        // --reads-per-batch
	ARG_SHMEM(272),                  // --shmem
	ARG_MM(273),                     // --mm
	ARG_MMSWEEP(274),                // --mmsweep
	ARG_FF(275),                     // --ff
	ARG_FR(276),                     // --fr
	ARG_RF(277),                     // --rf
	ARG_NO_MIXED(278),               // --no-mixed
	ARG_NO_DISCORDANT(279),          // --no-discordant
	ARG_CACHE_LIM(280),              // --
	ARG_CACHE_SZ(281),               // --
	ARG_NO_FW(282),                  // --nofw
	ARG_NO_RC(283),                  // --norc
	ARG_SKIP(284),                   // --skip
	ARG_ONETWO(285),                 // --12
	ARG_PHRED64(286),                // --phred64
	ARG_PHRED33(287),                // --phred33
	ARG_HADOOPOUT(288),              // --hadoopout
	ARG_FULLREF(289),                // --fullref
	ARG_USAGE(290),                  // --usage
	ARG_SNPPHRED(291),               // --snpphred
	ARG_SNPFRAC(292),                // --snpfrac
	ARG_SAM_NO_QNAME_TRUNC(293),     // --sam-no-qname-trunc
	ARG_SAM_OMIT_SEC_SEQ(294),       // --sam-omit-sec-seq
	ARG_SAM_NOHEAD(295),             // --sam-noHD/--sam-nohead
	ARG_SAM_NOSQ(296),               // --sam-nosq/--sam-noSQ
	ARG_SAM_RG(297),                 // --sam-rg
	ARG_SAM_RGID(298),               // --sam-rg-id
	ARG_GAP_BAR(299),                // --gbar
	ARG_QUALS1(300),                 // --Q1
	ARG_QUALS2(301),                 // --Q2
	ARG_QSEQ(302),                   // --qseq
	ARG_SEED_SUMM(303),              // --seed-summary
	ARG_SC_UNMAPPED(304),            // --soft-clipped-unmapped-tlen
	ARG_OVERHANG(305),               // --overhang
	ARG_NO_CACHE(306),               // --no-cache
	ARG_USE_CACHE(307),              // --cache
	ARG_NOISY_HPOLY(308),            // --454/--ion-torrent
	ARG_LOCAL(309),                  // --local
	ARG_END_TO_END(310),             // --end-to-end
	ARG_SCAN_NARROWED(311),          // --scan-narrowed
	ARG_QC_FILTER(312),              // --qc-filter
	ARG_BWA_SW_LIKE(313),            // --bwa-sw-like
	ARG_MULTISEED_IVAL(314),         // --multiseed
	ARG_SCORE_MIN(315),              // --score-min
	ARG_SCORE_MA(316),               // --ma
	ARG_SCORE_MMP(317),              // --mm
	ARG_SCORE_NP(318),               // --nm
	ARG_SCORE_RDG(319),              // --rdg
	ARG_SCORE_RFG(320),              // --rfg
	ARG_N_CEIL(321),                 // --n-ceil
	ARG_DPAD(322),                   // --dpad
	ARG_SAM_PRINT_YI(323),           // --mapq-print-inputs
	ARG_ALIGN_POLICY(324),           // --policy
	ARG_PRESET_VERY_FAST(325),       // --very-fast
	ARG_PRESET_FAST(326),            // --fast
	ARG_PRESET_SENSITIVE(327),       // --sensitive
	ARG_PRESET_VERY_SENSITIVE(328),  // --very-sensitive
	ARG_PRESET_VERY_FAST_LOCAL(329),      // --very-fast-local
	ARG_PRESET_FAST_LOCAL(330),           // --fast-local
	ARG_PRESET_SENSITIVE_LOCAL(331),      // --sensitive-local
	ARG_PRESET_VERY_SENSITIVE_LOCAL(332), // --very-sensitive-local
	ARG_IGNORE_QUALS(333),           // --ignore-quals
	ARG_DESC(334),                   // --arg-desc
	ARG_TAB5(335),                   // --tab5
	ARG_TAB6(336),                   // --tab6
	ARG_WRAPPER(337),                // --wrapper
	ARG_DOVETAIL(338),               // --dovetail
	ARG_NO_DOVETAIL(339),            // --no-dovetail
	ARG_CONTAIN(340),                // --contain
	ARG_NO_CONTAIN(341),             // --no-contain
	ARG_OVERLAP(342),                // --overlap
	ARG_NO_OVERLAP(343),             // --no-overlap
	ARG_MAPQ_V(344),                 // --mapq-v
	ARG_SSE8(345),                   // --sse8
	ARG_SSE8_NO(346),                // --no-sse8
	ARG_UNGAPPED(347),               // --ungapped
	ARG_UNGAPPED_NO(348),            // --no-ungapped
	ARG_TIGHTEN(349),                // --tighten
	ARG_UNGAP_THRESH(350),           // --ungap-thresh
	ARG_EXACT_UPFRONT(351),          // --exact-upfront
	ARG_1MM_UPFRONT(352),            // --1mm-upfront
	ARG_EXACT_UPFRONT_NO(353),       // --no-exact-upfront
	ARG_1MM_UPFRONT_NO(354),         // --no-1mm-upfront
	ARG_1MM_MINLEN(355),             // --1mm-minlen
	ARG_VERSION(356),                // --version
	ARG_SEED_OFF(357),               // --seed-off
	ARG_SEED_BOOST_THRESH(358),      // --seed-boost
	ARG_READ_TIMES(359),             // --read-times
	ARG_EXTEND_ITERS(360),           // --extends
	ARG_DP_MATE_STREAK_THRESH(361),  // --db-mate-streak
	ARG_DP_FAIL_STREAK_THRESH(362),  // --dp-fail-streak
	ARG_UG_FAIL_STREAK_THRESH(363),  // --ug-fail-streak
	ARG_EE_FAIL_STREAK_THRESH(364),  // --ee-fail-streak
	ARG_DP_FAIL_THRESH(365),         // --dp-fails
	ARG_UG_FAIL_THRESH(366),         // --ug-fails
	ARG_MAPQ_EX(367),                // --mapq-extra
	ARG_NO_EXTEND(368),              // --no-extend
	ARG_REORDER(369),                // --reorder
	ARG_SHOW_RAND_SEED(370),         // --show-rand-seed
	ARG_READ_PASSTHRU(371),          // --passthrough
	ARG_SAMPLE(372),                 // --sample
	ARG_CP_MIN(373),                 // --cp-min
	ARG_CP_IVAL(374),                // --cp-ival
	ARG_TRI(375),                    // --tri
	ARG_LOCAL_SEED_CACHE_SZ(376),    // --local-seed-cache-sz
	ARG_CURRENT_SEED_CACHE_SZ(377),  // --seed-cache-sz
	ARG_SAM_NO_UNAL(378),            // --no-unal
	ARG_NON_DETERMINISTIC(379),      // --non-deterministic
	ARG_TEST_25(380),                // --test-25
	ARG_DESC_KB(381),                // --desc-kb
	ARG_DESC_LANDING(382),           // --desc-landing
	ARG_DESC_EXP(383),               // --desc-exp
	ARG_DESC_PRIORITIZE(384),        // --desc-prioritize
	ARG_DESC_FMOPS(385),             // --desc-fmops
	ARG_LOG_DP(386),                 // --log-dp
	ARG_LOG_DP_OPP(387),             // --log-dp-opp
	ARG_XEQ(388),                    // --xeq
	ARG_THREAD_CEILING(389),         // --thread-ceiling
	ARG_THREAD_PIDDIR(390),          // --thread-piddir
	ARG_INTERLEAVED_FASTQ(391);       // --interleaved
	
	private int x;
	Opts(int y) {x = y;}
}
